package fastech.oshi.gui;

import fastech.core.login.TelaAdicional;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.util.List;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author igor
 */
public class OshiGui extends javax.swing.JFrame {
        private Point point = new Point();

    Oshi oshi = new Oshi();
    /**
     * Creates new form OshiGui
     */
    public OshiGui() {
        initComponents();
    }
    static boolean maximized = true;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblValueMemory = new javax.swing.JLabel();
        jpbValueMemory = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpbValueDisk = new javax.swing.JProgressBar();
        lblValueDisk = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblProcCpu = new javax.swing.JLabel();
        lblProcPid = new javax.swing.JLabel();
        lblProcName = new javax.swing.JLabel();
        lblProcMem = new javax.swing.JLabel();
        lblProcPid1 = new javax.swing.JLabel();
        lblProcPid2 = new javax.swing.JLabel();
        lblProcPid3 = new javax.swing.JLabel();
        lblProcPid4 = new javax.swing.JLabel();
        lblProcCpu1 = new javax.swing.JLabel();
        lblProcCpu2 = new javax.swing.JLabel();
        lblProcCpu3 = new javax.swing.JLabel();
        lblProcCpu4 = new javax.swing.JLabel();
        lblProcMem1 = new javax.swing.JLabel();
        lblProcMem2 = new javax.swing.JLabel();
        lblProcMem3 = new javax.swing.JLabel();
        lblProcMem4 = new javax.swing.JLabel();
        lblProcName1 = new javax.swing.JLabel();
        lblProcName2 = new javax.swing.JLabel();
        lblProcName3 = new javax.swing.JLabel();
        lblProcName4 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        iconMinMaxClose = new javax.swing.JPanel();
        buttonClose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        buttonCloseMax = new javax.swing.JPanel();
        buttonMax = new javax.swing.JPanel();
        fullMax = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        menuIcon = new javax.swing.JPanel();
        lineHideMenu = new javax.swing.JPanel();
        hideMenu = new javax.swing.JPanel();
        buttonmenu = new javax.swing.JLabel();
        lineseting = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lineHideSettingto = new javax.swing.JPanel();
        buttonSeting2 = new javax.swing.JLabel();
        setting3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        setting = new javax.swing.JPanel();
        buttonSeting = new javax.swing.JLabel();
        buttonSeting3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpbValueCpu = new javax.swing.JProgressBar();
        lblValueCpu = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(73, 128, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dashboard Oshi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 320, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(25, 29, 74));
        jLabel3.setText("Memória");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 17, -1, -1));
        jPanel4.add(lblValueMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 59, 128, 15));

        jpbValueMemory.setBackground(new java.awt.Color(73, 128, 242));
        jpbValueMemory.setStringPainted(true);
        jPanel4.add(jpbValueMemory, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 92, 306, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 330, 190));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(25, 29, 74));
        jLabel5.setText("Disco");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 17, -1, -1));

        jpbValueDisk.setBackground(new java.awt.Color(73, 128, 242));
        jpbValueDisk.setStringPainted(true);
        jPanel6.add(jpbValueDisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 145, 299, -1));
        jPanel6.add(lblValueDisk, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 114, 128, 15));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 350, 230));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(25, 29, 74));
        jLabel6.setText("Processos");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 17, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 113, -1, 116));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("PID");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 85, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 113, -1, 116));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("%CPU");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 85, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("%MEM");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 85, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("NOME");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 85, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 51, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 113, -1, 116));
        jPanel7.add(lblProcCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 138, 51, 16));
        jPanel7.add(lblProcPid, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 113, 44, 15));
        jPanel7.add(lblProcName, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 113, 75, 16));
        jPanel7.add(lblProcMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 113, 49, 16));
        jPanel7.add(lblProcPid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 137, 44, 15));
        jPanel7.add(lblProcPid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 185, 44, 15));
        jPanel7.add(lblProcPid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 161, 44, 15));
        jPanel7.add(lblProcPid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 214, 44, 15));
        jPanel7.add(lblProcCpu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 113, 51, 16));
        jPanel7.add(lblProcCpu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 163, 51, 16));
        jPanel7.add(lblProcCpu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 188, 51, 16));
        jPanel7.add(lblProcCpu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 213, 51, 16));
        jPanel7.add(lblProcMem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 138, 49, 16));
        jPanel7.add(lblProcMem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 163, 49, 16));
        jPanel7.add(lblProcMem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 188, 49, 16));
        jPanel7.add(lblProcMem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 213, 49, 16));
        jPanel7.add(lblProcName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 138, 75, 16));
        jPanel7.add(lblProcName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 163, 75, 16));
        jPanel7.add(lblProcName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 188, 75, 16));
        jPanel7.add(lblProcName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 213, 75, 16));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 330, 340, 230));

        header.setBackground(new java.awt.Color(5, 10, 46));
        header.setPreferredSize(new java.awt.Dimension(800, 50));
        header.setLayout(new java.awt.BorderLayout());

        iconMinMaxClose.setBackground(new java.awt.Color(5, 10, 46));
        iconMinMaxClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonClose.setBackground(new java.awt.Color(5, 10, 46));
        buttonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCloseMouseClicked(evt);
            }
        });
        buttonClose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_32px.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        buttonClose.add(close, java.awt.BorderLayout.CENTER);

        iconMinMaxClose.add(buttonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        buttonCloseMax.setBackground(new java.awt.Color(5, 10, 46));
        buttonCloseMax.setLayout(new java.awt.BorderLayout());
        iconMinMaxClose.add(buttonCloseMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        buttonMax.setBackground(new java.awt.Color(5, 10, 46));
        buttonMax.setLayout(new java.awt.BorderLayout());

        fullMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/full_screen_32px.png"))); // NOI18N
        fullMax.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fullMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullMaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullMaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullMaxMouseExited(evt);
            }
        });
        buttonMax.add(fullMax, java.awt.BorderLayout.CENTER);

        iconMinMaxClose.add(buttonMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        header.add(iconMinMaxClose, java.awt.BorderLayout.LINE_END);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header.add(jLabel10, java.awt.BorderLayout.LINE_START);

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        menuIcon.setBackground(new java.awt.Color(5, 10, 46));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lineHideMenu.setBackground(new java.awt.Color(5, 10, 46));
        lineHideMenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout lineHideMenuLayout = new javax.swing.GroupLayout(lineHideMenu);
        lineHideMenu.setLayout(lineHideMenuLayout);
        lineHideMenuLayout.setHorizontalGroup(
            lineHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        lineHideMenuLayout.setVerticalGroup(
            lineHideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon.add(lineHideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 10));

        hideMenu.setBackground(new java.awt.Color(5, 10, 46));
        hideMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hideMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hideMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideMenuMouseExited(evt);
            }
        });

        buttonmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back_32px.png"))); // NOI18N

        javax.swing.GroupLayout hideMenuLayout = new javax.swing.GroupLayout(hideMenu);
        hideMenu.setLayout(hideMenuLayout);
        hideMenuLayout.setHorizontalGroup(
            hideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );
        hideMenuLayout.setVerticalGroup(
            hideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonmenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menuIcon.add(hideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        lineseting.setBackground(new java.awt.Color(5, 10, 46));
        lineseting.setPreferredSize(new java.awt.Dimension(50, 5));

        jPanel9.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout linesetingLayout = new javax.swing.GroupLayout(lineseting);
        lineseting.setLayout(linesetingLayout);
        linesetingLayout.setHorizontalGroup(
            linesetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        linesetingLayout.setVerticalGroup(
            linesetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linesetingLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        menuIcon.add(lineseting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 50, -1));

        lineHideSettingto.setBackground(new java.awt.Color(5, 10, 46));
        lineHideSettingto.setLayout(new java.awt.BorderLayout());
        menuIcon.add(lineHideSettingto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, -1));

        buttonSeting2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonSeting2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings_32px.png"))); // NOI18N
        buttonSeting2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuIcon.add(buttonSeting2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 50, 50));

        setting3.setBackground(new java.awt.Color(5, 10, 46));
        setting3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setting3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setting3MouseExited(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user_35px.png"))); // NOI18N
        jLabel11.setText("jLabel5");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout setting3Layout = new javax.swing.GroupLayout(setting3);
        setting3.setLayout(setting3Layout);
        setting3Layout.setHorizontalGroup(
            setting3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setting3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        setting3Layout.setVerticalGroup(
            setting3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        menuIcon.add(setting3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 50, 50));

        setting.setBackground(new java.awt.Color(5, 10, 46));
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout settingLayout = new javax.swing.GroupLayout(setting);
        setting.setLayout(settingLayout);
        settingLayout.setHorizontalGroup(
            settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        settingLayout.setVerticalGroup(
            settingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        menuIcon.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 50, -1));

        buttonSeting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuIcon.add(buttonSeting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 40, 40));

        buttonSeting3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonSeting3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/combo_chart_35px.png"))); // NOI18N
        buttonSeting3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonSeting3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSeting3MouseClicked(evt);
            }
        });
        menuIcon.add(buttonSeting3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 50, 50));

        jPanel1.add(menuIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, -1, 550));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(25, 29, 74));
        jLabel4.setText("CPU");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 17, -1, -1));

        jpbValueCpu.setBackground(new java.awt.Color(73, 128, 242));
        jpbValueCpu.setStringPainted(true);
        jPanel5.add(jpbValueCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 107, 303, -1));
        jPanel5.add(lblValueCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 77, 128, 14));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 350, 190));

        jLabel12.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Powerd by: Fastech");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 570, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 590));

        setSize(new java.awt.Dimension(788, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        printValues();
    }//GEN-LAST:event_formWindowOpened

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited

    }//GEN-LAST:event_closeMouseExited

    private void buttonCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_buttonCloseMouseClicked

    private void fullMaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullMaxMouseClicked

        if(maximized){

            OshiGui.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            OshiGui.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximized = false;
        }else{

            setExtendedState(JFrame.NORMAL);

            maximized = true;
        }

    }//GEN-LAST:event_fullMaxMouseClicked

    private void fullMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullMaxMouseEntered

    }//GEN-LAST:event_fullMaxMouseEntered

    private void fullMaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullMaxMouseExited
    }//GEN-LAST:event_fullMaxMouseExited

    private void hideMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuMouseClicked

      new TelaAdicional().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_hideMenuMouseClicked

    private void hideMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuMouseEntered

    }//GEN-LAST:event_hideMenuMouseEntered

    private void hideMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuMouseExited

    }//GEN-LAST:event_hideMenuMouseExited

    private void setting3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setting3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_setting3MouseEntered

    private void setting3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setting3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_setting3MouseExited

    private void settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseEntered

    }//GEN-LAST:event_settingMouseEntered

    private void settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseExited

    }//GEN-LAST:event_settingMouseExited

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
      Point p = this.getLocation();
      
      this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();       
    }//GEN-LAST:event_formMousePressed

    private void buttonSeting3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSeting3MouseClicked

        new OshiGui().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonSeting3MouseClicked

            /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OshiGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OshiGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OshiGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OshiGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OshiGui().setVisible(true);
            }
        });
    }

    public void printValues() {
        printValueCpu();
        printValueMemory();
        printValueDisk();
        printProcCpu();
        printProcPid();
        printProcMem();
        printProcName();
    }
    
    public void printValueCpu() {
        Integer valueCpu = oshi.getValuesProcessor();
        jpbValueCpu.setValue(valueCpu);
    }
    
    public void printValueMemory() {
        Integer valueMemory = oshi.getValuesMemory();
        jpbValueMemory.setValue(valueMemory);
    }
    
    public void printValueDisk() {
        Integer valueDisk = oshi.getValuesFileSystem();
        jpbValueDisk.setValue(valueDisk);
    }
    
    public void printProcCpu() {
        List<String> procCpu = oshi.getValuesProcCpu();
        lblProcCpu.setText("");
        String text = "";
        for(int i = 0; i < 5; i++) {
            switch (i) {
                case 0:
                    lblProcCpu.setText(procCpu.get(i));
                    break;
                case 1:
                    lblProcCpu1.setText(procCpu.get(i));
                    break;
                case 2:
                    lblProcCpu2.setText(procCpu.get(i));
                    break;
                case 3:
                    lblProcCpu3.setText(procCpu.get(i));
                    break;
                case 4:
                    lblProcCpu4.setText(procCpu.get(i));
                    break;
                default:
                    break;
            }
        }
    }
    public void printProcPid() {
        List<String> procPid = oshi.getValuesProcPid();
        String text = "";
        for(int i = 0; i < 5; i++) {
            switch (i) {
                case 0:
                    lblProcPid.setText(procPid.get(i));
                    break;
                case 1:
                    lblProcPid1.setText(procPid.get(i));
                    break;
                case 2:
                    lblProcPid2.setText(procPid.get(i));
                    break;
                case 3:
                    lblProcPid3.setText(procPid.get(i));
                    break;
                case 4:
                    lblProcPid4.setText(procPid.get(i));
                    break;
                default:
                    break;
            }
        }
    }
    public void printProcMem() {
        List<String> procMem = oshi.getValuesProcMem();
        for(int i = 0; i < 5; i++) {
            switch (i) {
                case 0:
                    lblProcMem.setText(procMem.get(i));
                    break;
                case 1:
                    lblProcMem1.setText(procMem.get(i));
                    break;
                case 2:
                    lblProcMem2.setText(procMem.get(i));
                    break;
                case 3:
                    lblProcMem3.setText(procMem.get(i));
                    break;
                case 4:
                    lblProcMem4.setText(procMem.get(i));
                    break;
                default:
                    break;
            }
        }
    }
    public void printProcName() {
        List<String> procName = oshi.getValuesProcName();
        for(int i = 0; i < 5; i++) {
            switch (i) {
                case 0:
                    lblProcName.setText(procName.get(i));
                    break;
                case 1:
                    lblProcName1.setText(procName.get(i));
                    break;
                case 2:
                    lblProcName2.setText(procName.get(i));
                    break;
                case 3:
                    lblProcName3.setText(procName.get(i));
                    break;
                case 4:
                    lblProcName4.setText(procName.get(i));
                    break;
                default:
                    break;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonClose;
    private javax.swing.JPanel buttonCloseMax;
    private javax.swing.JPanel buttonMax;
    private javax.swing.JLabel buttonSeting;
    private javax.swing.JLabel buttonSeting2;
    private javax.swing.JLabel buttonSeting3;
    private javax.swing.JLabel buttonmenu;
    private javax.swing.JLabel close;
    private javax.swing.JLabel fullMax;
    private javax.swing.JPanel header;
    private javax.swing.JPanel hideMenu;
    private javax.swing.JPanel iconMinMaxClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jpbValueCpu;
    private javax.swing.JProgressBar jpbValueDisk;
    private javax.swing.JProgressBar jpbValueMemory;
    private javax.swing.JLabel lblProcCpu;
    private javax.swing.JLabel lblProcCpu1;
    private javax.swing.JLabel lblProcCpu2;
    private javax.swing.JLabel lblProcCpu3;
    private javax.swing.JLabel lblProcCpu4;
    private javax.swing.JLabel lblProcMem;
    private javax.swing.JLabel lblProcMem1;
    private javax.swing.JLabel lblProcMem2;
    private javax.swing.JLabel lblProcMem3;
    private javax.swing.JLabel lblProcMem4;
    private javax.swing.JLabel lblProcName;
    private javax.swing.JLabel lblProcName1;
    private javax.swing.JLabel lblProcName2;
    private javax.swing.JLabel lblProcName3;
    private javax.swing.JLabel lblProcName4;
    private javax.swing.JLabel lblProcPid;
    private javax.swing.JLabel lblProcPid1;
    private javax.swing.JLabel lblProcPid2;
    private javax.swing.JLabel lblProcPid3;
    private javax.swing.JLabel lblProcPid4;
    private javax.swing.JLabel lblValueCpu;
    private javax.swing.JLabel lblValueDisk;
    private javax.swing.JLabel lblValueMemory;
    private javax.swing.JPanel lineHideMenu;
    private javax.swing.JPanel lineHideSettingto;
    private javax.swing.JPanel lineseting;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JPanel setting;
    private javax.swing.JPanel setting3;
    // End of variables declaration//GEN-END:variables
}
