-- MySQL Script generated by MySQL Workbench
-- seg 19 out 2020 20:40:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Fastech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Fastech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Fastech` DEFAULT CHARACTER SET utf8 ;
USE `Fastech` ;

-- -----------------------------------------------------
-- Table `Fastech`.`Establishment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fastech`.`Establishment` (
  `idEstablishment` INT NOT NULL,
  `City` VARCHAR(45) NULL,
  `ZipCode` CHAR(9) NULL,
  `Street` VARCHAR(45) NULL,
  `EstablishmentNumber` VARCHAR(5) NULL,
  PRIMARY KEY (`idEstablishment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fastech`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fastech`.`User` (
  `idUser` INT NOT NULL,
  `nameUser` VARCHAR(45) NULL,
  `loginUser` VARCHAR(45) NULL,
  `passwordUser` VARCHAR(45) NULL,
  `fkestablishmentUser` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_Usuario_Estabelecimento1_idx` (`fkestablishmentUser` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Estabelecimento1`
    FOREIGN KEY (`fkestablishmentUser`)
    REFERENCES `Fastech`.`Establishment` (`idEstablishment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fastech`.`Machine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fastech`.`Machine` (
  `idMachine` INT NOT NULL,
  `processadorMachine` TINYINT NULL,
  `Memory` TINYINT NULL,
  `discoMachine` TINYINT NULL,
  PRIMARY KEY (`idMachine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fastech`.`componets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fastech`.`componets` (
  `idcomponets` INT NOT NULL,
  `descriptions` VARCHAR(45) NULL,
  PRIMARY KEY (`idcomponets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fastech`.`Datas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fastech`.`Datas` (
  `idData` INT NOT NULL,
  `dtMoment` DATETIME NULL,
  `componets_idcomponets` INT NOT NULL,
  `Machine_idMachine` INT NOT NULL,
  PRIMARY KEY (`idData`),
  INDEX `fk_Datas_componets1_idx` (`componets_idcomponets` ASC) VISIBLE,
  INDEX `fk_Datas_Machine1_idx` (`Machine_idMachine` ASC) VISIBLE,
  CONSTRAINT `fk_Datas_componets1`
    FOREIGN KEY (`componets_idcomponets`)
    REFERENCES `Fastech`.`componets` (`idcomponets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Datas_Machine1`
    FOREIGN KEY (`Machine_idMachine`)
    REFERENCES `Fastech`.`Machine` (`idMachine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fastech`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fastech`.`Test` (
  `idTest` INT NOT NULL,
  `dtMoment` DATETIME NULL,
  `CpuTest` TINYINT NULL,
  `MemoryTest` TINYINT NULL,
  `discTest` TINYINT NULL,
  `pingTest` TINYINT NULL,
  PRIMARY KEY (`idTest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fastech`.`teste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fastech`.`teste` (
  `idData` INT NOT NULL,
  `dtMoment` DATETIME NULL,
  `componets_idcomponets` INT NOT NULL,
  `Machine_idMachine` INT NOT NULL,
  PRIMARY KEY (`idData`),
  INDEX `fk_Datas_componets1_idx` (`componets_idcomponets` ASC) VISIBLE,
  INDEX `fk_Datas_Machine1_idx` (`Machine_idMachine` ASC) VISIBLE,
  CONSTRAINT `fk_Datas_componets10`
    FOREIGN KEY (`componets_idcomponets`)
    REFERENCES `Fastech`.`componets` (`idcomponets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Datas_Machine10`
    FOREIGN KEY (`Machine_idMachine`)
    REFERENCES `Fastech`.`Machine` (`idMachine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
